spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/graddesign?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root123###
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 1000
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  thymeleaf:
      cache: false
      enabled: true
      encoding: UTF-8
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html
      servlet:
        content-type: text/html
#  rabbitmq:
#    host: 172.26.2.41
#    port:5672
#    username: guest
#    password: guest
#    virtual-host: /
#    listener:
#      simple:
#        concurrency: 10
#        max-concurrency: 10
#        prefetch: 1
#        auto-startup: true
#        default-requeue-rejected: true
#    template:
#      retry:
#        enabled: true
#        initial-interval: 1000
#        max-attempts: 3
#        max-interval: 10000
#        multiplier: 1.0


mybatis:
  mapperLocations: classpath:com/mooe/grad/dao/*.xml
  type-aliases-package: com.mooe.grad.domain
  configuration:
    map-underscore-tuo-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#pagehelper:
 # helperDialect: mysql
  #reasonable: true
  #supportMethodsArguments: true
  #params: count=countSql
#-----------redis-----------------
redis:
  host: localhost
  port: 6379
  timeout: 10
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500